######################################################################
# Automatically generated by qmake (3.1) Tue Sep 10 14:09:45 2024
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TEMPLATE = app
TARGET = qtImageViewer
INCLUDEPATH += .

# Input
SOURCES += qtimageViewer.cpp
